### PR TITLE
CRC-CCITT32 and CMake

### PR DESCRIPTION
**Pull request by jopadan**
Moves old build system to Makefile.libcrc and includes the new changes
CCITT32-CRC based on https://github.com/dgilman/macutils

### CODE REVIEW

**Comment by lammertb** [comment]
Will this compile now without problems on systems without CMake installed?

**Comment by jopadan** [comment]
Yes you have to use
```c
make -f Makefile.libcrc
```

but it is missing generating the .pc file in Makefile.libcrc

Everything else should be working.

**Comment by jopadan** [comment]
Just renamed all the Makefile self references as a temporary solution.
Maybe you should try to find a way to get the Makefile filename at make
execution

**Comment by jopadan** [comment]
Why is the request closed again? I just updated the existing Makefile
to Makefile.crc to and updated INSTALL with new build instructions
for both build systems to exist alongside.

**Pull request closed without merging**
