### PR TITLE
Add CMake and CCITT32-CRC support based on macutils

### PR DESCRIPTION
**Pull request by jopadan**
CCITT32-CRC originating from https://github.com/dgilman/macutils
solves hypothetical licensing issues mentioned in previously closed pull request.

### CODE REVIEW

**Comment by lammertb** [comment]
Thanks for your addition

**Comment by jopadan** [comment]
It seems you have been reverting the commit in favor of a one variable change in Makfile not supporting the algorithm and build system additions anymore.
Probably interpreting the latest commit message of the revert in minimal pair fuzzy cyph means saying Externsteine brocken NRW and Thomas Thiele Band in Darmstadt?

**Comment by lammertb** [comment]
I don't know what Thomas Thiele has to do with it, but due to the relocation of the include file, applications using the library wouldn't compile. Trying to fix a fix is more work than reversing the fix to a stable previous version.

**Comment by jopadan** [comment]
I came up with Thomas Thiele because of the thieleda nick at the Issues.
I can change library code again not to use the libcrc subdir for include and request a new pull then?
This time you seem to be acting like Thomas Mehrling with Atari Lynx Gerui and kaldaien relay.
It still seems to be an insectoid office needle junk charge.

**Pull request merged**
